### ISSUE TITLE
Example APKs?

### ISSUE THREAD

**Issue by janpio** [tomthecarrot/arcore-for-all#1]
Any ready made APKs using this available? I'ld love to play with it...

**Comment by tomthecarrot** [comment]
Thanks! Just added a sample APK to the repo.

**Comment by janpio** [comment]
Awesome.

Unfortunately I get

> Parse error
> There was a problem parsing the package.

**Comment by janpio** [comment]
Nexus 5, 6.0.1
Download in Chrome, open the .apk. (developer activated)

(So wouldn't be too surprised if the device is just too old of course)

**Comment by tomthecarrot** [comment]
Ah. The minimum SDK is Nougat (7.0). Sorry about that :|

**Comment by janpio** [comment]
Damn.

Any chance this will be "fixable" as well?

(Might want to document that btw)

**Comment by tomthecarrot** [comment]
I'll give it a try! :)

**Comment by MZorzy** [comment]
[test]
installed on Samsung Tab S2 (android 7.0) , see "Made with unity" then ask to restart app...
added "tango core" ( https://github.com/google-ar/arcore-android-sdk/releases/download/sdk-preview/arcore-preview.apk ) but this crash and then same issue with you example.

**Comment by MZorzy** [comment]
#2 #3 #4
