### ISSUE TITLE
S8+ - Doesn't find surfaces

### ISSUE THREAD

**Issue by Jastman** [tomthecarrot/arcore-for-all#12]
The app launches and runs on my S8+ when I build and deploy the app thru Unity, after replacing the .aar file. However, while the app is running, all I see on the screen is the camera and the message "Searching for surfaces..." No indication that it sees any surfaces

**Comment by tomthecarrot** [comment]
This appears to be an ARCore tracking issue, not a library issue. This modification is only designed to enable the library on officially-unsupported devices, but once launched does not affect ARCore tracking.

**Comment by muizzadeni** [comment]
Same problem on my Galaxy S5
