### ISSUE TITLE
Works on OnePlus 5 (Snapdragon 835)

### ISSUE THREAD

**Issue by MishaalRahmanXDA** [tomthecarrot/arcore-for-all#27]
As shown in our article here: https://www.xda-developers.com/arcore-for-all-google-augmented-reality/

**Comment by tomthecarrot** [comment]
Thank you for your report!

**Comment by sagarkar** [comment]
It was working on OnePlus 5, but stopped working after 4.5.14 update. 
https://youtu.be/UYErFnAVhnE?t=2

**Comment by sagarkar** [comment]
Okay, Did a factory Reset and all is working fine. Wondering what happened there!!
