### ISSUE TITLE
Cant install on g4 play marshmellow

### ISSUE THREAD

**Issue by greatjack1** [tomthecarrot/arcore-for-all#36]
I am trying to install the helloar.apk as well as the modified ar core preview apk and I keep on getting the "INSTALL FAILED OLDER SDK"  error when installing through adb. Any Ideas?

**Comment by tomthecarrot** [comment]
The ARCore library currently supports Android 7.0 (Nougat) and above. It is currently not available on Android 6.0 (Marshmallow), although there might eventaully be ways around that also.
