### ISSUE TITLE
Can't run on redmi note 4 7.0 nougat

### ISSUE THREAD

**Issue by bpradana** [tomthecarrot/arcore-for-all#4]
App stopped working after unity splash screen

**Comment by Hitschm** [comment]
Tried sample app on OnePlus 3. Also crashed on splash screen.

**Comment by tomthecarrot** [comment]
Could you attach logcat output of the crash? Please also keep in mind that this is experimental.

**Comment by tomthecarrot** [comment]
Please try with this suggestion:
https://github.com/tomthecarrot/arcore-for-all/issues/3#issuecomment-326015422

**Comment by tazzkiller** [comment]
@tomthecarrot For the Oneplus 3 LogCat error on com.tango is no config file exist. But if i change my build.prop for declare my OP3  is a pixel phone, tango service and sample works.

**Comment by tomthecarrot** [comment]
Thank you for sharing your logs @tazzkiller. The following line may be of importance:
`helpers.cc:288 Hardcoded CAD model unavailable for device kUnknownDevice`

I wonder if they hardcode CAD models (whatever that means in this context, possibly 3D computer aided design models) for each known dev device.
`Hardcoded CAD model fallback: Enabled`

It's interesting that when you set your `build.prop` device name to Pixel, ARCore works just fine. Maybe your device _can_ run the CAD model for Pixel, but not the fallback model.

**Comment by tomthecarrot** [comment]
Luckily, there is now a pattern in most of the new logs submitted: this CAD model error is crashing Tango Service on many devices. However, it's a good sign that @tazzkiller's OnePlus 3 was functional after changing the device name in `build.prop` to "Pixel". Tango Service seems to be looking for device-specific calibration models, and when those are not found, it attempts to use a fallback (which is not present in the filesystem).

**Comment by MarcAnt01** [comment]
Seems for OP3 is no longer working in Pie-based Roms
