### ISSUE TITLE
can you take a API_23(6.0) "modified ARCore Service APK"

### ISSUE THREAD

**Issue by feng612266** [tomthecarrot/arcore-for-all#43]
Hi,can you take a API_23(6.0) "modified ARCore Service APK",thank you!

**Comment by tomthecarrot** [comment]
The ARCore library currently supports Android 7.0 (Nougat) and above. It is currently not available on Android 6.0 (Marshmallow), although there might eventaully be ways around that also.

**Comment by feng612266** [comment]
@tomthecarrot ok,thank you,i  upgrade phonte system ,and retrial。
