### ISSUE TITLE
Which phones are working..?

### ISSUE THREAD

**Issue by nkkollaw** [tomthecarrot/arcore-for-all#53]
I'm wondering if there a list of phones that are working..? It would be useful to have a list in the README.

I'm considering buying a phone for AR, but I really dislike the S8, and I can't find the Pixel at any store here in Poland.

**Comment by Hitschm** [comment]
As far as I can see it's not working on any phones other then two supported from Google.
The S8+ apparently works in some versions with arcore-for-all.

I'm now buying an S8 for development. Not the biggest fan of that phone either but the Pixel even less so. The S8 is just nicer to show off prototypes and I think slim bezels might look better for AR content. And finding a Pixel for a good price is really hard here in Switzerland too.

**Comment by nkkollaw** [comment]
Ah, gotcha.

I thought it was working for some phones.

I'll wait :-)
