### ISSUE TITLE
Doesn't install in S8+

### ISSUE THREAD

**Issue by SamyMann** [tomthecarrot/arcore-for-all#60]
I downloaded the file and when I run the installation it finishes but I can't find any Icon of the App to open it.

**Comment by SamyMann** [comment]
I am really new to android programing

**Comment by J4S0Nc** [comment]
Pretty sure this is just a library that replaces the google version (no app to run).

https://developers.google.com/ar/develop/java/getting-started

**Comment by tomthecarrot** [comment]
@J4S0Nc is correct; ARCore Service ("Tango Core") is an Android Service and thus has no Activities or visible apps to run.
