### ISSUE TITLE
Not working on Samsung S8+ (SM-G9550)

### ISSUE THREAD

**Issue by m0o0scar** [tomthecarrot/arcore-for-all#76]
# About the phone

* Device: Samsung S8+
* Model number: SM-G9550
* Android version: 7.0
* Build number: NRD90M.G9550ZCU1AQH6

# About the problem

## What happened?

1. Successfully build and deploy the Hello ARCore Unity example scene following these guides: [Getting Started with Unity | ARCore](https://developers.google.com/ar/develop/unity/getting-started) and [ARCore for all - Unity Installation](https://github.com/tomthecarrot/arcore-for-all/blob/master/README.md);
2. Hello ARCore app runs on the phone;
3. "Made with Unity" splash screen is shown;
4. The app crash.
5. Restart or reinstall the app won't solve.

## What's in the log?

These are what I saw in the logcat during the app crash:

```
Force finishing activity com.oscartong.xr.helloar/com.unity3d.player.UnityPlayerActivity
Exception thrown during pause
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
 	at android.os.BinderProxy.transactNative(Native Method)
 	at android.os.BinderProxy.transact(Binder.java:628)
 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:876)
 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1465)
 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4415)
 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:4207)
 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2354)
 	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:735)
 	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:571)
 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:407)
 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:346)
 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:17238)
 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

Process com.oscartong.xr.helloar (pid 14968) has died(113,1053)
```

**Comment by moscartong** [comment]
So is there a plan or ETA for supporting S8+? Or we have to wait for further release of ARCore from Google?

**Comment by tomthecarrot** [comment]
It works on my S8+ and IIRC other people have confirmed it working on S8+. However, some S8+ devices do not work. We have an experiment that IMO is getting close to making ARCore run on most devices, albeit without accurate calibration at first. Please feel free to jump into the branch referenced in the README and help us!

**Comment by pennomi** [comment]
I can also confirm it works on my S8+. I found the app crashed when I didn't follow Google's Unity setup instructions to the letter. (For instance, you have to turn off multithreaded rendering in Unity.)

**Comment by moscartong** [comment]
@pennomi I did follow Google's instruction when setting up the unity project. I'll try the branch then :blush:

**Comment by detomato** [comment]
It works on my S8+(South East Asia) too.

**Comment by hanqingzhen** [comment]
Unlucky, my S8+(NRD90M.G9550ZCU1AQH6) does not work.It was stoped at screen with "Searching for surfaces ..."

**Comment by January23** [comment]
S8+ G9550ZCU1AQF7 dose not work.

09-26 17:59:48.439 5010-5010/com.google.ar.core.examples.java.helloar D/SurfaceView: Relayout returned: oldFrame=[0,63][1080,2220] newFrame=[0,0][1080,2220] result=0x21 surface={Surface(name=null)/@0xb5466e7 isValid=true 546920659968}
09-26 17:59:48.471 5010-5010/com.google.ar.core.examples.java.helloar V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@d967aed nm : com.google.ar.core.examples.java.helloar ic=null
09-26 17:59:49.041 5010-5051/com.google.ar.core.examples.java.helloar W/System.err: android.os.DeadObjectException
09-26 17:59:49.041 5010-5051/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
09-26 17:59:49.041 5010-5051/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transact(Binder.java:628)
09-26 17:59:49.041 5010-5051/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.ITangoVhs$Stub$Proxy.getTrackingSurface(ITangoVhs.java:111)
09-26 17:59:49.041 5010-5051/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.TangoVhs.getTrackingSurface(TangoVhs.java:81)
09-26 17:59:49.042 5010-5051/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.tango.jni.TangoCameraNative$2.run(TangoCameraNative.java:88)
09-26 17:59:49.042 5010-5051/com.google.ar.core.examples.java.helloar W/System.err:     at java.lang.Thread.run(Thread.java:762)
09-26 17:59:49.042 5010-5051/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
09-26 17:59:49.042 5010-5051/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: tracking_surface == nullptr! Could break AR usecases

**Comment by tschussler** [comment]
I have successfully deployed using a Samsung SM-G955U1 model S8+ (unlocked model)

**Comment by solidcinu** [comment]
tschussler could You please explain me step by step what do You mean by that please??:)

**Comment by detomato** [comment]
I have 2 S8+, works on one, but not the other. Guessed its depends on your luck.

**Comment by moscartong** [comment]
@detomato Any difference on system version and other stuffs?
