### ISSUE TITLE
***UPDATE*  Working on oneplus 3 

### ISSUE THREAD

**Issue by rohit1231** [tomthecarrot/arcore-for-all#88]
android version 7.1.1

"The device does not support AR" is the message displayed when I try to open the HelloAR app

**Comment by rohit1231** [comment]
@tomthecarrot hey I followed this link
https://forum.xda-developers.com/mobile-vr/google-daydream-vr/spoofing-daydream-compatible-device-t3534943

and helloar app works fine on one plus3 now.
Spread the news 
May be you can test it on any other device

**Comment by rohit1231** [comment]
tested for app built using unity as well, works fine. 
bug noticed: sometimes app requires phone restart to behave properly.

**Comment by Calence** [comment]
1. After I installed sample.apk, I touched the icon on my phone that crashed!
2. First, in my Android project, simply replace the Google-provided `arcore_client.aar` with the one in this repo. When running on my phone, it shows "Searching for surfaces...". How to do if?
