### ISSUE TITLE
[Camera upside-down] Nexus 5X with Pixel build.prop device name

### ISSUE THREAD

**Issue by abdullahibneat** [tomthecarrot/arcore-for-all#93]
It works, however camera is upside down... I was expecting ARCore to use Google's newest camera API which should fix the problem (more about it from [The Verge](https://www.theverge.com/2015/11/9/9696774/google-nexus-5x-upside-down-camera)).

The way I changed the device name is by using [Magisk Root](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445) and using the [Pixelify Magisk Mod](https://forum.xda-developers.com/mobile-vr/google-daydream-vr/spoofing-daydream-compatible-device-t3534943) (which is nothing more than a build.prop with device name to "marlin") to trick apps to think your device is a Pixel.

I attach a screenshot below (from the Sketchfab app, which recently added ARCore support).
![screenshot_20171112-193446](https://user-images.githubusercontent.com/7048592/32702546-b003a5ce-c7e0-11e7-83a0-a69d75c6081e.png)

**Comment by abdullahibneat** [comment]
Logcat from running the sample HelloAR core with your edits.
[logcat.txt](https://github.com/tomthecarrot/arcore-for-all/files/1465068/logcat.txt)

Also, I tried to run [WebAR on ARCore](https://github.com/google-ar/WebARonARCore).... Interestingly, the camera is displayed correctly, but no surfaces are detected...

Lastly, I forgot to mention I got the Tango Core directly from Google's repo... Am I supposed to use a custom version of it?

**Comment by tomthecarrot** [comment]
I added a [modified service APK](https://github.com/tomthecarrot/arcore-for-all/blob/service-mod/service-mod/arcore-preview-modified.apk) to the repo, which is based on research in the [service-mod](https://github.com/tomthecarrot/arcore-for-all/tree/service-mod) branch. Your progress is promising, so please let us know if the new service works!

**Comment by KeiShadow** [comment]
in my project i solve this problem like this:
1) i set in manifest the app will be in landscape mode
2) in OnCameraFrame im used this method
 Core.flip(mRgba,mFlip,1);
 Core.flip(mFlip,mRgba,0);
3) Works very well:(
